# Generated by Django 2.2.24 on 2023-08-02 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='issue',
            field=models.CharField(choices=[('deposit', 'Depositing Money'), ('trading', 'Trading Coins'), ('assets', 'Assets not showing in my portfolio'), ('other', 'Other')], default='other', max_length=255),
        ),
    ]
