# Generated by Django 2.2.24 on 2023-05-21 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='icon',
        ),
    ]
