# Generated by Django 2.2.24 on 2023-05-21 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0002_remove_cryptocurrency_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='chart',
        ),
    ]
