# Generated by Django 2.2.24 on 2023-05-22 15:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0004_auto_20230521_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='icon',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='icon'),
        ),
    ]
