# Generated by Django 2.2.24 on 2023-05-22 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0005_cryptocurrency_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='icon',
            field=models.TextField(),
        ),
    ]
