# Generated by Django 2.2.24 on 2023-05-22 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0006_auto_20230522_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='sparkline',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='icon',
            field=models.TextField(default=''),
        ),
    ]
