# Generated by Django 2.2.24 on 2023-05-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0008_auto_20230531_1647'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='yesterday_price',
        ),
        migrations.AlterField(
            model_name='cryptocurrency',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
