# Generated by Django 2.2.24 on 2023-05-31 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0009_auto_20230531_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
