# Generated by Django 2.2.24 on 2023-05-31 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0010_auto_20230531_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='PopularCryptoCurrency',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('coinhub.cryptocurrency',),
        ),
    ]
