# Generated by Django 2.2.24 on 2023-05-31 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0011_popularcryptocurrency'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PopularCryptoCurrency',
        ),
        migrations.CreateModel(
            name='PopularCryptoCurrency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('change', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('icon', models.TextField(default='')),
                ('sparkline', models.TextField(default='')),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
            ],
        ),
    ]
