# Generated by Django 2.2.24 on 2023-06-01 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0013_topgainercrypto_toplosercrypto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
