# Generated by Django 2.2.24 on 2023-06-02 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0014_cryptocurrency_volume'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('chart_1h', models.TextField(default='')),
                ('chart_1d', models.TextField(default='')),
                ('chart_1w', models.TextField(default='')),
                ('chart_1m', models.TextField(default='')),
                ('chart_1y', models.TextField(default='')),
                ('chart_all', models.TextField(default='')),
                ('market_cap', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('volume', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('supply', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('hold_time', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('rank', models.CharField(max_length=100)),
                ('all_time_high', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('change_1h', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('change_24h', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('change_7d', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('ath_change', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('about', models.TextField(default='To find out more about this project visit the resources.')),
            ],
        ),
        migrations.AddField(
            model_name='popularcryptocurrency',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='topgainercrypto',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='toplosercrypto',
            name='volume',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
