# Generated by Django 2.2.24 on 2023-06-03 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0016_cryptocurrency_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptodetail',
            name='hold_time',
        ),
        migrations.RemoveField(
            model_name='cryptodetail',
            name='supply',
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='circulating_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='color',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='fully_diluted_market_cap',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='icon',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='links',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='max_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='symbol',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='total_supply',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='uuid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='website_url',
            field=models.CharField(default='', max_length=100),
        ),
    ]
