# Generated by Django 2.2.24 on 2023-06-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0017_auto_20230603_1508'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodetail',
            name='ath_time_stamp',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
