# Generated by Django 2.2.24 on 2023-06-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0018_cryptodetail_ath_time_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodetail',
            name='weekly_incline',
            field=models.BooleanField(default=True),
        ),
    ]
