# Generated by Django 2.2.24 on 2023-06-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0019_cryptodetail_weekly_incline'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptodetail',
            name='dayly_incline',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cryptodetail',
            name='hourly_incline',
            field=models.BooleanField(default=True),
        ),
    ]
