# Generated by Django 2.2.24 on 2023-06-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0020_auto_20230615_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptocurrency',
            name='trading_pairs',
            field=models.TextField(default=''),
        ),
    ]
