# Generated by Django 2.2.24 on 2023-06-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0021_cryptocurrency_trading_pairs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptocurrency',
            name='trading_pairs',
        ),
        migrations.AddField(
            model_name='cryptocurrency',
            name='euro_trading_pair',
            field=models.CharField(default='', max_length=100),
        ),
    ]
