# Generated by Django 2.2.24 on 2023-06-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0024_auto_20230622_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='balance_history',
            field=models.TextField(default=''),
        ),
    ]
