# Generated by Django 2.2.24 on 2023-06-23 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0026_auto_20230623_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='balance_history',
            field=models.TextField(default=''),
        ),
    ]
