# Generated by Django 2.2.24 on 2023-06-24 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0030_auto_20230624_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='user_id',
        ),
    ]
