# Generated by Django 2.2.24 on 2023-06-24 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0031_remove_customuser_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='price_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
