# Generated by Django 2.2.24 on 2023-07-07 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0033_auto_20230707_1350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='asset_balance_history',
            new_name='amount_history',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='price_change',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='total_balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='balance_history',
        ),
    ]
