# Generated by Django 2.2.24 on 2023-07-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0034_auto_20230707_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='total_amount',
            field=models.DecimalField(decimal_places=8, default=0, max_digits=40),
        ),
    ]
