# Generated by Django 2.2.24 on 2023-07-31 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0036_auto_20230707_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
