# Generated by Django 2.2.24 on 2023-07-31 15:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0037_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
