# Generated by Django 2.2.24 on 2023-07-31 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0038_transaction_uuid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='uuid',
            new_name='transaction_uuid',
        ),
    ]
