# Generated by Django 2.2.24 on 2023-08-03 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0039_auto_20230731_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptocurrency',
            name='rank',
            field=models.IntegerField(max_length=100),
        ),
    ]
