# Generated by Django 2.2.24 on 2023-08-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0042_asset_current_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_change',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
