# Generated by Django 2.2.24 on 2023-08-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinhub', '0043_asset_current_change'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=40),
        ),
    ]
